<!DOCTYPE html>
<html>
<body>
<br>
<?php
echo Form::open('persona/nuevo');
echo Html::img('reg.png','una imagen');
echo "<br>";
echo "idalumno";
echo "<br>";
echo Form::text('idalumno');
echo "<br>";
echo "nombre";
echo "<br>";
echo Form::text('nombre');
echo "<br>";
echo "apellido";
echo "<br>";
echo Form::text('apellido');
echo "<br>";
echo "edad";
echo "<br>";
echo Form::text('edad');
echo "<br>";
echo "telefono";
echo "<br>";
echo Form::text('telefono');
echo "<br>";
echo "sexo";
echo "<br>";
echo Form::text('sexo');
echo "<br>";
echo "direccion";
echo "<br>";
echo Form::text('direccion');
echo "<br>";
echo "contraseña";
echo "<br>";
echo Form::button('registrar');
?>
</body>
</html>