<!DOCTYPE html>
<html>
<body>
<br>
<h1>Registrate!</h1>
<p>idalumno</p>
<?php
echo Form::text('idalumno');
echo "<br>";
echo "nombre";
echo "<br>";
echo Form::text('nombre');
echo "<br>";
echo "apellido";
echo "<br>";
echo Form::text('apellido');
echo "<br>";
echo "edad";
echo "<br>";
echo Form::text('edad');
echo "<br>";
echo "telefono";
echo "<br>";
echo Form::text('telefono');
echo "<br>";
echo "sexo";
echo "<br>";
echo Form::text('sexo');
echo "<br>";
echo "direccion";
echo "<br>";
echo Form::text('direccion');
echo "<br>";
echo "contraseña";
echo "<br>";
echo Form::button('registrar');
echo Form::submitImage('reg.png'); //Crea un botón con la imagen 'botones/edit.gif'
?>
</body>
</html>